version: "3.7"

services:
  postgres:
    image: docker.io/bitnami/postgresql:14
    user: root
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=django_join_unrelated
      - POSTGRESQL_PASSWORD=django_join_unrelated
      - POSTGRESQL_DATABASE=django_join_unrelated
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  pg_data:
